#Fichier de configuration de FactionPicks

#CustomModelData des différentes pioches :
CMD:
  #Pioche permettant de miner les spawners
  Pioche à Spawner : 1
  #Pioche permettant de miner en 3x3
  Pioche MultiBlock : 2