#Fichier de configuration de FactionPicks

#CustomModelData des différentes pioches :
CMD:
  #Pioche permettant de miner les spawners
  SpawnerPick : 1
  #Pioche permettant de miner en 3x3
  RangePick : 2